export const BUSINESS = {
  name: "Beach Road Pizza",
  phoneDisplay: "08 8186 5991",
  phoneHref: "tel:+61881865991",
  address: "29B Beach Road, Christies Beach SA 5165",
  mapsUrl:
    "https://www.google.com/maps/search/?api=1&query=29B+Beach+Road+Christies+Beach+SA+5165",
  orderUrl: "https://beachroadpizza.com.au/",
  uberUrl:
    "https://www.ubereats.com/au/store/beach-road-pizza/030AM-V6QQKLRdzYjvj5RQ",
  doorDashUrl:
    "https://www.doordash.com/en-AU/store/beach-road-pizza-christies-beach-35409369/",
};

export const HOURS = [
  { days: "Monday to Thursday", hours: "3:00 pm to 9:00 pm" },
  { days: "Friday and Saturday", hours: "3:00 pm to 9:30 pm" },
  { days: "Sunday", hours: "3:00 pm to 9:30 pm" },
];

export const REVIEWS = [
  {
    quote: "Hot and fresh. I will definitely come back!",
    author: "Harpreet K.",
    source: "Google review",
  },
  {
    quote: "The best tasting pizzas around. Great value for money and delivered hot.",
    author: "Mick M.",
    source: "Google review",
  },
];

export const DEALS = [
  {
    title: "$25 Large Deal",
    detail: "1 traditional large pizza, garlic bread and a 1.25L drink.",
    note: "Beach Road Pizza menu deal.",
    href: BUSINESS.orderUrl,
    action: "Order this deal",
  },
  {
    title: "$32 Family Deal",
    detail: "1 traditional family pizza, garlic bread and a 1.25L drink.",
    note: "Beach Road Pizza menu deal.",
    href: BUSINESS.orderUrl,
    action: "Order this deal",
  },
  {
    title: "$37 Party Deal",
    detail: "1 traditional party pizza, garlic bread and a 1.25L drink.",
    note: "Beach Road Pizza menu deal.",
    href: BUSINESS.orderUrl,
    action: "Order this deal",
  },
  {
    title: "$40 Double Deal",
    detail: "2 traditional large pizzas, garlic bread and a 1.25L drink.",
    note: "Beach Road Pizza menu deal.",
    href: BUSINESS.orderUrl,
    action: "Order this deal",
  },
  {
    title: "$47 Triple Deal",
    detail: "3 traditional large pizzas for an easy group order.",
    note: "Beach Road Pizza menu deal.",
    href: BUSINESS.orderUrl,
    action: "Order this deal",
  },
  {
    title: "$54 Family Deal",
    detail: "2 traditional family pizzas, garlic bread and a 1.25L drink.",
    note: "Beach Road Pizza menu deal.",
    href: BUSINESS.orderUrl,
    action: "Order this deal",
  },
  {
    title: "$49 Gourmet Deal",
    detail: "2 gourmet large pizzas with garlic bread.",
    note: "Beach Road Pizza menu deal.",
    href: BUSINESS.orderUrl,
    action: "Order this deal",
  },
  {
    title: "$49 Vegan Deal",
    detail: "2 vegan large pizzas with vegan garlic bread.",
    note: "Beach Road Pizza menu deal.",
    href: BUSINESS.orderUrl,
    action: "Order this deal",
  },
  {
    title: "$25 Schnitzel Deal",
    detail: "2 schnitzels with chips, gravy and a 1.25L drink.",
    note: "Beach Road Pizza menu deal.",
    href: BUSINESS.orderUrl,
    action: "Order this deal",
  },
];

export type MenuCategory =
  | "Traditional pizzas"
  | "Gourmet pizzas"
  | "Vegan pizzas"
  | "Sides"
  | "Schnitzels"
  | "Pastas"
  | "Drinks and treats";

export type MenuItem = {
  name: string;
  category: MenuCategory;
  description: string;
  price: string;
  sizes?: string;
  vegan?: boolean;
  popular?: boolean;
  image?: string;
};

const TRADITIONAL_SIZES = "Small $14.50 | Large $18.50 | Family $26.50 | Party $31.50";
const GOURMET_SIZES = "Small $18.50 | Large $22.50 | Family $30.50 | Party $34.50";
const VEGAN_SIZES = "Small $18.50 | Large $22.50 | Family $30.50 | Party $34.50";

export const MENU: MenuItem[] = [
  {
    name: "Cheese Lover",
    category: "Traditional pizzas",
    description: "Double cheese on a tomato base.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
    popular: true,
    image: "/images/food/Beach Road Pizza_Cheesy Double.jpg",
  },
  {
    name: "Margherita",
    category: "Traditional pizzas",
    description: "Double cheese, sliced tomato and herbs on a tomato base.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
    popular: true,
    image: "/images/food/Beach Road Pizza_Margherita.jpg",
  },
  {
    name: "Cheesy Garlic",
    category: "Traditional pizzas",
    description: "Double cheese and crushed garlic on a tomato base.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
  },
  {
    name: "Ham and Cheese",
    category: "Traditional pizzas",
    description: "Cheese and ham on a tomato base.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
    image: "/images/food/Beach Road Pizza_Ham & Cheese.jpg",
  },
  {
    name: "Ham and Pineapple",
    category: "Traditional pizzas",
    description: "Cheese, ham and pineapple on a tomato base.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
    popular: true,
  },
  {
    name: "Meat Lover",
    category: "Traditional pizzas",
    description: "Cheese, ham, pepperoni and bacon on a tomato base.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
    popular: true,
    image: "/images/food/Beach Road Pizza_BBQ Meat Lovers.jpg",
  },
  {
    name: "Supreme",
    category: "Traditional pizzas",
    description: "Ham, onion, mushroom, capsicum, pepperoni, bacon, pineapple and cheese.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
    popular: true,
  },
  {
    name: "Hot and Spicy",
    category: "Traditional pizzas",
    description: "Ham, capsicum, pepperoni, olives, jalapeños and chilli flakes.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
  },
  {
    name: "Vegetarian",
    category: "Traditional pizzas",
    description: "Onion, mushroom, capsicum, tomato, pineapple, olives and herbs.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
    image: "/images/food/Beach Road Pizza_Vegetarian.jpg",
  },
  {
    name: "Aussie",
    category: "Traditional pizzas",
    description: "Cheese, onion, bacon and egg on a tomato base.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
    image: "/images/food/Beach Road Pizza_Aussie.jpg",
  },
  {
    name: "Italian",
    category: "Traditional pizzas",
    description: "Ham, mushroom, capsicum, pepperoni, olives and cheese.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
  },
  {
    name: "BBQ Beef",
    category: "Traditional pizzas",
    description: "Cheese, onion, beef and bacon on a BBQ base.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
  },
  {
    name: "Seafood",
    category: "Traditional pizzas",
    description: "Cheese, prawns, mussels, garlic and herbs.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
  },
  {
    name: "BBQ Chicken",
    category: "Traditional pizzas",
    description: "Cheese and roast chicken on a BBQ base.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
    image: "/images/food/Beach Road Pizza_Chicken.jpg",
  },
  {
    name: "Chicken Hawaiian",
    category: "Traditional pizzas",
    description: "Cheese, roast chicken, pineapple and herbs.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
  },
  {
    name: "Chicken Supreme",
    category: "Traditional pizzas",
    description: "Mushroom, capsicum, pepperoni, roast chicken, pineapple and cheese.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
  },
  {
    name: "Sweet Chilli Chicken",
    category: "Traditional pizzas",
    description: "Onion, capsicum, roast chicken, pineapple and sweet chilli sauce.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
  },
  {
    name: "Butter Chicken Pizza",
    category: "Traditional pizzas",
    description: "Butter chicken sauce, onion, roast chicken and cheese.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
    popular: true,
  },
  {
    name: "Pepperoni",
    category: "Traditional pizzas",
    description: "Cheese and pepperoni on a tomato base.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
    popular: true,
    image: "/images/food/Beach Road Pizza_Pepporini.jpg",
  },
  {
    name: "Peri Peri Chicken",
    category: "Traditional pizzas",
    description: "Roast chicken, onion, spinach and peri peri sauce.",
    price: "From $14.50",
    sizes: TRADITIONAL_SIZES,
    image: "/images/food/Beach Road Pizza_Peri Peri Chicken.jpg",
  },
  {
    name: "Beach Special",
    category: "Gourmet pizzas",
    description: "Semidried tomato, ham, pepperoni, roasted capsicum, prawns and pineapple.",
    price: "From $18.50",
    sizes: GOURMET_SIZES,
    popular: true,
  },
  {
    name: "Mega Meat",
    category: "Gourmet pizzas",
    description: "Pepperoni, ham, roast chicken, beef and bacon on a BBQ base.",
    price: "From $18.50",
    sizes: GOURMET_SIZES,
    popular: true,
  },
  {
    name: "The Boss",
    category: "Gourmet pizzas",
    description: "Semidried tomato, mushroom, pepperoni, ham, chicken, capsicum and tomato.",
    price: "From $18.50",
    sizes: GOURMET_SIZES,
  },
  {
    name: "Lamb Yiros Pizza",
    category: "Gourmet pizzas",
    description: "Marinated lamb, onion, tomato, herbs and garlic sauce.",
    price: "From $18.50",
    sizes: GOURMET_SIZES,
    popular: true,
    image: "/images/food/Beach Road Pizza_Lamb Yiros.jpg",
  },
  {
    name: "Combo Yiros Pizza",
    category: "Gourmet pizzas",
    description: "Lamb, roast chicken, onion, tomato, herbs and garlic sauce.",
    price: "From $18.50",
    sizes: GOURMET_SIZES,
  },
  {
    name: "Ultimate Yiros Pizza",
    category: "Gourmet pizzas",
    description: "Lamb, roast chicken, bacon, onion and garlic sauce on a BBQ base.",
    price: "From $18.50",
    sizes: GOURMET_SIZES,
  },
  {
    name: "Satay Chicken",
    category: "Gourmet pizzas",
    description: "Onion, roasted capsicum, roast chicken and pineapple on a satay base.",
    price: "From $18.50",
    sizes: GOURMET_SIZES,
    image: "/images/food/Beach Road Pizza_Satay Chicken.jpg",
  },
  {
    name: "Vegorama",
    category: "Gourmet pizzas",
    description: "Semidried tomato, mushroom, eggplant, pumpkin, cherry tomato, olives and herbs.",
    price: "From $18.50",
    sizes: GOURMET_SIZES,
  },
  {
    name: "Christies Special",
    category: "Gourmet pizzas",
    description: "Semidried tomato, mushroom, ham, roast chicken, prawns and pineapple.",
    price: "From $18.50",
    sizes: GOURMET_SIZES,
  },
  {
    name: "Garlic Prawn",
    category: "Gourmet pizzas",
    description: "King prawns, onion, cherry tomato, herbs and garlic aioli sauce.",
    price: "From $18.50",
    sizes: GOURMET_SIZES,
  },
  {
    name: "Chicken Pesto",
    category: "Gourmet pizzas",
    description: "Mushroom, capsicum, roast chicken, cherry tomato and pesto sauce.",
    price: "From $18.50",
    sizes: GOURMET_SIZES,
  },
  {
    name: "Moroccan Lamb",
    category: "Gourmet pizzas",
    description: "Moroccan lamb, red onion, cherry tomato and garlic aioli sauce.",
    price: "From $18.50",
    sizes: GOURMET_SIZES,
  },
  {
    name: "Crumbed Chicken Zing",
    category: "Gourmet pizzas",
    description: "Crumbed chicken, red onion, pineapple and special sauce.",
    price: "$21 large",
  },
  {
    name: "Vegan Margherita",
    category: "Vegan pizzas",
    description: "Double vegan cheese, cherry tomato and herbs.",
    price: "From $18.50",
    sizes: VEGAN_SIZES,
    vegan: true,
  },
  {
    name: "Vegan BBQ Chicken",
    category: "Vegan pizzas",
    description: "Vegan cheese, onion, vegan chicken, pineapple and herbs.",
    price: "From $18.50",
    sizes: VEGAN_SIZES,
    vegan: true,
    popular: true,
  },
  {
    name: "Vegan Chicken Supreme",
    category: "Vegan pizzas",
    description: "Vegan cheese, onion, mushroom, capsicum, vegan chicken and pineapple.",
    price: "From $18.50",
    sizes: VEGAN_SIZES,
    vegan: true,
  },
  {
    name: "Vegan BBQ Beef",
    category: "Vegan pizzas",
    description: "Vegan cheese, onion, vegan beef and cherry tomato on a BBQ base.",
    price: "From $18.50",
    sizes: VEGAN_SIZES,
    vegan: true,
  },
  {
    name: "Vegan Lamb Yiros",
    category: "Vegan pizzas",
    description: "Vegan lamb, onion, tomato, herbs and vegan garlic sauce.",
    price: "From $18.50",
    sizes: VEGAN_SIZES,
    vegan: true,
    popular: true,
  },
  {
    name: "Vegan Veggie",
    category: "Vegan pizzas",
    description: "Semidried tomato, mushroom, capsicum, eggplant, pumpkin, pineapple and herbs.",
    price: "From $18.50",
    sizes: "Small $16 | Large $21 | Family $28 | Party $35",
    vegan: true,
  },
  {
    name: "Vegan Pepperoni",
    category: "Vegan pizzas",
    description: "Vegan cheese and vegan pepperoni.",
    price: "From $18.50",
    sizes: VEGAN_SIZES,
    vegan: true,
  },
  {
    name: "Vegan Ham and Pineapple",
    category: "Vegan pizzas",
    description: "Vegan cheese, vegan ham and pineapple.",
    price: "From $18.50",
    sizes: VEGAN_SIZES,
    vegan: true,
  },
  {
    name: "Vegan Meat Lover",
    category: "Vegan pizzas",
    description: "Vegan cheese, vegan ham, vegan beef and vegan bacon.",
    price: "From $18.50",
    sizes: VEGAN_SIZES,
    vegan: true,
  },
  {
    name: "Vegan Supreme",
    category: "Vegan pizzas",
    description: "Vegan ham, onion, mushroom, capsicum, pineapple and vegan bacon.",
    price: "From $18.50",
    sizes: VEGAN_SIZES,
    vegan: true,
  },
  {
    name: "Vegan Pesto Delight",
    category: "Vegan pizzas",
    description: "Capsicum, pineapple, cherry tomato, pumpkin and vegan pesto.",
    price: "From $18.50",
    sizes: VEGAN_SIZES,
    vegan: true,
  },
  {
    name: "Vegan Pulled Pork",
    category: "Vegan pizzas",
    description: "Vegan cheese, onion, vegan pulled pork and vegan bacon.",
    price: "From $18.50",
    sizes: VEGAN_SIZES,
    vegan: true,
  },
  {
    name: "Vegan Chicken Zing",
    category: "Vegan pizzas",
    description: "Crumbed vegan chicken, red onion, pineapple and vegan special sauce.",
    price: "From $18.50",
    sizes: VEGAN_SIZES,
    vegan: true,
  },
  {
    name: "Garlic Bread",
    category: "Sides",
    description: "Baked garlic bread with herbs.",
    price: "$4.50",
  },
  {
    name: "Cheesy Garlic Bread",
    category: "Sides",
    description: "Baked garlic bread with herbs and cheese.",
    price: "$6",
    popular: true,
  },
  {
    name: "BBQ Chicken Wings",
    category: "Sides",
    description: "BBQ-flavoured chicken wings.",
    price: "$13",
    image: "/images/food/Beach Road Pizza_BBQ Chicken Wings.jpg",
  },
  {
    name: "Chips",
    category: "Sides",
    description: "A generous serve of hot chips.",
    price: "$9.90",
    image: "/images/food/Beach Road Pizza_Chips.jpg",
  },
  {
    name: "Wedges",
    category: "Sides",
    description: "Wedges with sweet chilli and sour cream.",
    price: "$10",
  },
  {
    name: "Loaded Wedges",
    category: "Sides",
    description: "Wedges with bacon, cheese, sweet chilli and sour cream.",
    price: "$15",
    image: "/images/food/Beach Road Pizza_Bacon & Wedges.jpg",
  },
  {
    name: "Chicken Nuggets",
    category: "Sides",
    description: "Breaded and deep-fried chicken nuggets.",
    price: "From $6",
    sizes: "6 pieces $6 | 10 pieces $9",
  },
  {
    name: "Chicken Nuggets and Chips",
    category: "Sides",
    description: "Six chicken nuggets with chips.",
    price: "$10",
  },
  {
    name: "Vegan Arancini Balls",
    category: "Sides",
    description: "Six vegan arancini balls.",
    price: "$8.50",
    vegan: true,
  },
  {
    name: "Vegan Nuggets",
    category: "Sides",
    description: "Six vegan nuggets.",
    price: "$9",
    vegan: true,
  },
  {
    name: "BBQ Ribs",
    category: "Sides",
    description: "BBQ ribs in half or full slab sizes.",
    price: "From $17",
    sizes: "Half slab $17 | Full slab $34",
  },
  {
    name: "Snitty Schnitzel",
    category: "Schnitzels",
    description: "Plain schnitzel with chips and gravy.",
    price: "$23.50",
  },
  {
    name: "Parmi Schnitzel",
    category: "Schnitzels",
    description: "Ham, cheese and Napoletana sauce with chips and gravy.",
    price: "$25.50",
  },
  {
    name: "BBQ Chicken Schnitzel",
    category: "Schnitzels",
    description: "Diced chicken, mushroom, onion, cheese and BBQ sauce with chips and gravy.",
    price: "$25.50",
  },
  {
    name: "Mexican Schnitzel",
    category: "Schnitzels",
    description: "Pepperoni, jalapeño, cheese and tomato sauce with chips and gravy.",
    price: "$23.50",
  },
  {
    name: "Bacon Bliss Schnitzel",
    category: "Schnitzels",
    description: "Bacon, onion and cheese with chips and gravy.",
    price: "$25.50",
  },
  {
    name: "Hawaiian Schnitzel",
    category: "Schnitzels",
    description: "Ham, pineapple and cheese with chips and gravy.",
    price: "$25.50",
  },
  {
    name: "Lamb Schnitzel",
    category: "Schnitzels",
    description: "Lamb, onion, tomato and cheese with chips and tzatziki.",
    price: "$28.50",
  },
  {
    name: "Spaghetti Bolognese",
    category: "Pastas",
    description: "Traditional meat sauce topped with parsley.",
    price: "$16",
  },
  {
    name: "Penne Carbonara",
    category: "Pastas",
    description: "Cream sauce and bacon topped with parsley.",
    price: "$17",
  },
  {
    name: "Penne Alla Panna",
    category: "Pastas",
    description: "Cream sauce, ham and mushroom topped with parsley.",
    price: "$16",
  },
  {
    name: "Penne Con Pollo",
    category: "Pastas",
    description: "Rosé sauce, chicken, bacon and broccoli topped with parsley.",
    price: "$16",
  },
  {
    name: "Penne Vegetarian",
    category: "Pastas",
    description: "Napoletana sauce, capsicum, onion, mushroom, spinach and broccoli.",
    price: "$16",
  },
  {
    name: "Penne Chicken and Mushroom",
    category: "Pastas",
    description: "Rosé sauce, chicken and mushroom topped with parsley.",
    price: "$16",
  },
  {
    name: "Penne Napoli",
    category: "Pastas",
    description: "Napoletana sauce, onion and olives topped with parsley.",
    price: "$14",
  },
  {
    name: "Penne Aglio Olio",
    category: "Pastas",
    description: "A mild cheese cream sauce and a kids' favourite.",
    price: "$14",
  },
  {
    name: "Bello",
    category: "Pastas",
    description: "Chicken, roasted capsicum, broccoli and pesto cream sauce.",
    price: "$17",
  },
  {
    name: "Marinara",
    category: "Pastas",
    description: "Prawns and mussels in a rosé sauce topped with parsley.",
    price: "$17",
  },
  {
    name: "Soft drink can",
    category: "Drinks and treats",
    description: "Selected Pepsi range cans, 375 ml.",
    price: "$3.50",
  },
  {
    name: "Soft drink bottle",
    category: "Drinks and treats",
    description: "Selected Pepsi and Schweppes range bottles, 1.25 L.",
    price: "$5.90",
  },
  {
    name: "Cool Ridge Water",
    category: "Drinks and treats",
    description: "Still bottled water, 750 ml.",
    price: "$4",
  },
  {
    name: "Ice-creams",
    category: "Drinks and treats",
    description: "A rotating freezer selection including favourites from $2.",
    price: "From $2",
  },
];

export const CATEGORIES: Array<"All" | MenuCategory> = [
  "All",
  "Traditional pizzas",
  "Gourmet pizzas",
  "Vegan pizzas",
  "Sides",
  "Schnitzels",
  "Pastas",
  "Drinks and treats",
];
